name: Deploy by Branch

on:

  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to run against"
        type: choice
        required: true
        options: [dev, stage, prod]

      component:
        description: "Terraform component"
        type: choice
        required: true
        options: [s3, networking]

      action:
        description: "Terraform action"
        type: choice
        required: true
        options: [plan, apply, destroy]

  pull_request:
    branches: [dev, stage, prod]

  push:
    branches: [dev, stage, prod]



permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-1

jobs:
  validate:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    environment: ${{ github.base_ref }}

    strategy:
      matrix:
        component: [s3, networking]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform -chdir=terraform/components/${{ matrix.component }} init

      - name: Terraform Format Check
        run: terraform -chdir=terraform/components/${{ matrix.component }} fmt -check

      - name: Terraform Validate
        run: terraform -chdir=terraform/components/${{ matrix.component }} validate
      
      - name: Terraform Security Scan
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: terraform/components/${{ matrix.component }}
          framework: terraform
          skip_check: CKV2_AWS_62,CKV_AWS_18,CKV_AWS_144,CKV_AWS_130,CKV2_AWS_12,CKV2_AWS_11

      - name: Terraform Plan
        run: |
          terraform -chdir=terraform/components/${{ matrix.component }} plan \
            -var="environment=${{ github.base_ref }}"

  deploy:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}

    strategy:
      matrix:
        component: [s3, networking]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-1

      - name: Confirm AWS account
        run: aws sts get-caller-identity

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform -chdir=terraform/components/${{ matrix.component }} init

      - name: Terraform Apply
        run: |
          terraform -chdir=terraform/components/${{ matrix.component }} apply \
            -var="environment=${{ github.ref_name }}" \
            -auto-approve


  manual:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Confirm AWS account
        run: aws sts get-caller-identity

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform -chdir=terraform/components/${{ inputs.component }} init

      - name: Terraform Plan
        if: inputs.action == 'plan'
        run: |
          terraform -chdir=terraform/components/${{ inputs.component }} plan \
            -var="environment=${{ inputs.environment }}"

      - name: Terraform Apply
        if: inputs.action == 'apply'
        run: |
          terraform -chdir=terraform/components/${{ inputs.component }} apply \
            -var="environment=${{ inputs.environment }}" \
            -auto-approve

      - name: Terraform Destroy
        if: inputs.action == 'destroy'
        run: |
          terraform -chdir=terraform/components/${{ inputs.component }} destroy \
            -var="environment=${{ inputs.environment }}" \
            -auto-approve

            